In [1]:
import matplotlib.pyplot as plt  
import numpy as np               
import pandas as pd              
from scipy import stats

# Data understanding

###  Leitura do dataset

In [2]:
listing = "dataset/listings.csv"
df = pd.read_csv(listing)
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,48154,Precioso apartamento con wifi,219476,Antonio,LA SAIDIA,MORVEDRE,39.48375,-0.37502,Entire home/apt,83.0,3,197,2025-09-15,1.08,4,150,26,VT-41540-V
1,137143,PENTHOUSE ON FRONT LINE BEACH,670775,Maria De La Piedad,POBLATS DEL SUD,EL SALER,39.36335,-0.31932,Entire home/apt,390.0,10,1,2013-07-02,0.01,5,20,0,VT32745V
2,149715,1900 Style Valencian Beach Home for 10px,5947,Susana Barbara,POBLATS MARITIMS,CABANYAL-CANYAMELAR,39.46746,-0.32813,Entire home/apt,245.0,2,313,2025-09-15,1.81,1,287,41,ESFCTU000046025000580569000000000000000000VT-3...
3,165971,★ Architectural touch! ★,791187,Inés,EXTRAMURS,LA ROQUETA,39.46790,-0.38206,Entire home/apt,124.0,5,576,2025-09-03,3.34,8,106,46,VT-32757-V
4,182221,Apartments Calatrava City Valencia,1315567,Chiara,CAMINS AL GRAU,AIORA,39.46343,-0.34325,Entire home/apt,137.0,3,9,2025-03-17,0.07,1,176,1,VT-38755-V

In [3]:
#converter last_review para datetime
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

df.describe(include="all").round(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,7.844000e+03,7844,7.844000e+03,7838,7844,7844,7844.000,7844.000,7844,6979.000,7844.000,7844.000,6867,6867.000,7844.000,7844.000,7844.000,4533
unique,NaN,7515,NaN,1764,19,85,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3988
top,NaN,Habitación en Valencia,NaN,Marta,POBLATS MARITIMS,CABANYAL-CANYAMELAR,NaN,NaN,Entire home/apt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VT-54221-V
freq,NaN,21,NaN,124,1471,750,NaN,NaN,5782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19
mean,8.243448e+17,NaN,2.890802e+08,NaN,NaN,NaN,39.467,-0.364,NaN,164.113,6.554,51.636,2025-05-23 07:31:16.277850624,1.695,12.325,185.951,13.353,NaN
min,4.815400e+04,NaN,5.947000e+03,NaN,NaN,NaN,39.280,-0.426,NaN,8.000,1.000,0.000,2013-07-02 00:00:00,0.010,1.000,0.000,0.000,NaN
25%,5.086848e+07,NaN,7.425452e+07,NaN,NaN,NaN,39.461,-0.380,NaN,71.000,1.000,3.000,2025-07-01 00:00:00,0.470,1.000,77.000,1.000,NaN
50%,1.020877e+18,NaN,2.292401e+08,NaN,NaN,NaN,39.469,-0.371,NaN,102.000,2.000,16.000,2025-08-28 00:00:00,1.170,3.000,179.000,6.000,NaN
75%,1.295046e+18,NaN,5.042718e+08,NaN,NaN,NaN,39.475,-0.344,NaN,140.000,5.000,58.250,2025-09-12 00:00:00,2.490,11.000,305.000,21.000,NaN
max,1.514336e+18,NaN,7.196722e+08,NaN,NaN,NaN,39.546,-0.276,NaN,40000.000,366.000,935.000,2025-09-23 00:00:00,37.710,103.000,365.000,367.000,NaN
std,5.535320e+17,NaN,2.288511e+08,NaN,NaN,NaN,0.019,0.023,NaN,732.639,18.756,86.940,NaN,1.666,20.771,120.086,17.752,NaN

### descrição inicial

In [13]:
quantiva_discretas = ["number_of_reviews_ltm", "number_of_reviews", "minimum_nights", "calculated_host_listings_count"]
quantiva_continuas = ["latitude", "longitude", "price", "reviews_per_month", "availability_365"]
qualitativas_nominais = ["neighbourhood_group", "neighbourhood", "host_name","room_type"]

df["availability_365"].head(10)

0    150
1     20
2    287
3    106
4    176
5    161
6    160
7     88
8      1
9     45
Name: availability_365, dtype: int64

In [ ]:
desc = df[quantiva_continuas].describe().round(3)

desc.loc["amplitude"] = (df[quantiva_continuas].max() - df[quantiva_continuas].min()).round(3)
desc.loc["IQR"] = (df[quantiva_continuas].quantile(0.75) - df[quantiva_continuas].quantile(0.25)).round(3)
desc.loc["assimetria"] = df[quantiva_continuas].skew().round(3)
desc.loc["curtose"] = df[quantiva_continuas].kurtosis().round(3)
desc.to_excel("tabela.xlsx")

,latitude,longitude,price,reviews_per_month,availability_365
count,7844.000,7844.000,6979.000,6867.000,7844.000
mean,39.467,-0.364,164.113,1.695,185.951
std,0.019,0.023,732.639,1.666,120.086
min,39.280,-0.426,8.000,0.010,0.000
25%,39.461,-0.380,71.000,0.470,77.000
50%,39.469,-0.371,102.000,1.170,179.000
75%,39.475,-0.344,140.000,2.490,305.000
max,39.546,-0.276,40000.000,37.710,365.000
amplitude,0.266,0.150,39992.000,37.700,365.000
IQR,0.013,0.036,69.000,2.020,228.000
assimetria,-4.843,0.372,29.441,3.414,-0.056
curtose,38.527,-0.568,1328.501,44.759,-1.420

Variável: number_of_reviews_ltm
Intervalo de variação: 367
Intervalo interquartil: 20.0
Assimetria: 2.868
Curtose: 25.877
--------------------------------------------------
Variável: number_of_reviews
Intervalo de variação: 935
Intervalo interquartil: 55.25
Assimetria: 3.038
Curtose: 11.98
--------------------------------------------------
Variável: minimum_nights
Intervalo de variação: 365
Intervalo interquartil: 4.0
Assimetria: 13.279
Curtose: 228.086
--------------------------------------------------
Variável: calculated_host_listings_count
Intervalo de variação: 102
Intervalo interquartil: 10.0
Assimetria: 2.504
Curtose: 5.893
--------------------------------------------------

In [7]:
for variavel in quantiva_continuas:
    print(f"Variável: {variavel}")
    print(f"Intervalo de variação: {df[variavel].max() - df[variavel].min()}")
    print(f"Intervalo interquartil: {(df[variavel].quantile(0.75) - df[variavel].quantile(0.25)).round(3)}")
    print(f"Assimetria: {df[variavel].skew().round(3)}")
    print(f"Curtose: {df[variavel].kurtosis().round(3)}")
    print("-" * 50)

Variável: latitude
Intervalo de variação: 0.2658036999999993
Intervalo interquartil: 0.013
Assimetria: -4.843
Curtose: 38.527
--------------------------------------------------
Variável: longitude
Intervalo de variação: 0.14955999999999997
Intervalo interquartil: 0.036
Assimetria: 0.372
Curtose: -0.568
--------------------------------------------------
Variável: price
Intervalo de variação: 39992.0
Intervalo interquartil: 69.0
Assimetria: 29.441
Curtose: 1328.501
--------------------------------------------------
Variável: reviews_per_month
Intervalo de variação: 37.7
Intervalo interquartil: 2.02
Assimetria: 3.414
Curtose: 44.759
--------------------------------------------------